"""

Revision ID: 142a4ca9c919
Revises: rbac_implementation_phase1
Create Date: 2025-09-24 12:07:44.111641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '142a4ca9c919'
down_revision: Union[str, None] = 'rbac_implementation_phase1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'EXECUTE', 'DEPLOY', 'EXPORT', 'IMPORT', 'SHARE', 'PUBLISH', 'ARCHIVE', 'RESTORE', 'MANAGE', 'GRANT', 'REVOKE', 'AUDIT', 'BREAK_GLASS', 'IMPERSONATE', 'EXPORT_FLOW', 'DEPLOY_ENVIRONMENT', 'INVITE_USERS', 'MODIFY_COMPONENT_SETTINGS', 'MANAGE_TOKENS', name='permissionaction'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'EXECUTE', 'DEPLOY', 'EXPORT', 'IMPORT', 'SHARE', 'PUBLISH', 'ARCHIVE', 'RESTORE', 'MANAGE', 'GRANT', 'REVOKE', 'AUDIT', 'BREAK_GLASS', 'IMPERSONATE', 'EXPORT_FLOW', 'DEPLOY_ENVIRONMENT', 'INVITE_USERS', 'MODIFY_COMPONENT_SETTINGS', 'MANAGE_TOKENS', name='permissionaction'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
